namespace AAEmu.PacketProxy;

/// <summary>
/// Friendly opcode names for the AA 2.0.1.7 Trion-r249376 build. Generated by
/// hand from the alpha emulator's CSOffsets / SCOffsets — extend as needed.
/// Returns "?" for opcodes we don't know about yet so the log still shows the
/// raw number for grepping.
/// </summary>
internal static class OpcodeNames
{
    public static string GameLookup(string direction, ushort opcode, byte level)
    {
        // We track only a handful for now — the ones we've been actively debugging.
        if (direction == "C->S")
        {
            return opcode switch
            {
                0x000 => "X2EnterWorldPacket",
                0x0DE => "CSAesXorKeyPacket",
                0x15C => "CSCreateCharacterPacket",
                0x139 => "CSPing?",
                0x18  => "CS_0x018",
                _ => $"?"
            };
        }

        return opcode switch
        {
            0x000 => "X2EnterWorldResponsePacket",
            0x00F => "SetGameTypePacket",
            0x068 => "SCRaceCongestionPacket",
            0x181 => "SCInitialConfigPacket",
            0x1A6 => "SCLevelRestrictionConfigPacket",
            0x201 => "SCTrionConfigPacket",
            0x222 => "SCCharacterListPacket",
            0x22E => "SCAccountAttendancePacket",
            0x25A => "SCGetSlotCountPacket",
            0x0A2 => "SCAccountAttributeConfigPacket",
            0x0E4 => "SCAccountInfoPacket",
            _ => $"?"
        };
    }

    public static string StreamLookup(string direction, ushort opcode)
    {
        if (direction == "C->S")
        {
            return opcode switch
            {
                0x001 => "CTJoinPacket",
                _ => $"?"
            };
        }
        return opcode switch
        {
            0x001 => "TCJoinResponsePacket",
            _ => $"?"
        };
    }
}
